### ISSUE TITLE
为啥能和github同步  有点不明白 

### ISSUE THREAD

**Issue by biningo** [broqiang/mdblog#12]
为啥能和github同步  有点不明白   希望大佬指点指点

**Comment by broqiang** [comment]
github 本身有钩子，每一个动作会有事件，比如我用的是 commit 事件，在github的仓库中提交后，会给我自己的项目发送一个 post 请求，通知我，我自己的项目再做下 git update 就可以了

**Comment by biningo** [comment]
哦哦 多谢多谢 我在看看
