### ISSUE TITLE
想用你的前端样式，可以吗。

### ISSUE THREAD

**Issue by rundaisc** [broqiang/mdblog#14]
看起来很舒服。我也准备自己写一个博客。前端是个大问题。想直接用你的，可以吗

**Comment by broqiang** [comment]
随意使用，我也是原生 bootstrap 随便改了几个变量，样式没有太多代码

**Comment by broqiang** [comment]
> 看起来很舒服。我也准备自己写一个博客。前端是个大问题。想直接用你的，可以吗

随意使用，我也是原生 bootstrap 随便改了几个变量，样式没有太多代码
